database:
  host: 35.231.254.21
  port: 3306
  username: root
  password: digitaltradingcards14
  databaseName: digital_trading_cards
jwt:
  key: jwt_digitaltradingcards
  aud: wisteria@ui
  iss: wisteria@api
